# Site wide configuration

title:            Mind Ramblings
locale:           en_US
url:              http://abinashmeher999.github.io
url:              http://localhost:4000


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Site owner
owner:
  name: Abinash Meher
  avatar: my-bio-photo.jpg
  bio: "An undergraduate student in Computer Science and Engineering at IIT Kharagpur, and student developer at Ruby Science Foundation"
  email: abinashdakshana999@gmail.com
  disqus-shortname: Abinash_Meher
  twitter: beenharsh999
  facebook: #abinashmeher999
  google:
    plus: AbinashMeher999
    analytics: UA-57345186-2
    verify: 
    ad-client: 
    ad-slot: 
  bing-verify: 
  github: abinashmeher999
  stackoverflow: #http://stackoverflow.com/users/123456/username
  linkedin: abinashmeher
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
